# 指定操作的镜像
FROM java:8
# 设定时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# 将jar包拷贝进去
RUN mkdir -p /sky_take_out/logs
COPY sky-server-1.0-SNAPSHOT.jar /sky_take_out/sky-server.jar
EXPOSE 8080

# 运行jar包
WORKDIR /sky_take_out
CMD ["java","-jar","sky-server.jar"]